### ISSUE TITLE
Incorrect flow information being updated when a flow runs multiple times per day.

### ISSUE THREAD

**Issue by richardpatersonGIT** [eomnl/sas-jobmon#13]
There appears to be an issue with flows which are scheduled to run multiple times per day. We have a flow which runs once per hour. What appears to happen is that a subsequent run of a flow overwrites the original execution date/time from the previous execution. The web interface also then changes the state of the already completed flow to 'running'. On completion both flows are now showing the same date and time. I have attached some images which should explain the issue. 
![1](https://user-images.githubusercontent.com/30265475/43704687-c7012f56-9960-11e8-80db-3f23e49afe03.png)
![2](https://user-images.githubusercontent.com/30265475/43704688-c72050c0-9960-11e8-9540-96cec8b71b56.png)

**Comment by bheinsius** [comment]
Hi Richard,

The app should have no problems with flows that are scheduled to run multiple times per day. It looks like there is a duplicate record somewhere. You may want to try and reinitialize the dimon data sets that get filled by the DI job since it aborted a few times because of the problem you had.

If that doesn't work you can try to recreate the issue. The report for this web page is created by the process flow **Flows** in the EG project **DIMonRT3.egp**.
Can you run it to see what is happening?

Regards,
Bart

**Comment by bheinsius** [comment]
Hi Richard,

Did you get this working? If so what was the solution?

Regards,
Bart

**Comment by richardpatersonGIT** [comment]
Hi Bart,

er...geen idee. DIMON is afgelopen week naar PROD overgezet dus Ik ga
vanuit dat er geen issue meer is. Ticket mag gesloten worden.

groet,

RIchard
